version: "3.0"

services:
  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    restart: always
    ports:
      - "9091:9091"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      - prom-network

networks:
  prom-network:
    driver: bridge
