groups:
  - name: cqh
    rules:
      - alert: cqh-test
        expr: dead_lift > 150
        for: 1m
        labels:
          status: warning
        annotations:
          summary: "{{$labels.instance}}:硬拉超标!light weight baby !!!"
          description: "{{$labels.instance}}:硬拉超标!light weight baby !!!"
